version: '3.4'

services:
  # ROS Noetic panther driver
  panther_driver:
    image: husarion/panther-driver
    container_name: panther_driver
    network_mode: host
    restart: on-failure
    environment:
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: roslaunch panther_driver driver.launch


  # ROS Noetic velocity manager
  velocity_manager:
    image: husarion/velocity-manager:noetic-latest
    container_name: velocity_manager
    tty: true   
    network_mode: host
    restart: on-failure
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
    command: rosrun velocity_manager velocity_manager_node


  # ROS Noetic joystick controller
  logitech-f710-joy-ros:
    build:
      context: ./../../
    container_name: logitech-f710-joy-ros
    tty: true   
    network_mode: host
    restart: on-failure
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
    devices:
      - /dev/input/js0
    command: roslaunch logitech_f710_joy_ros joy_teleop.launch


  # ROS Noetic ROS master
  ros-master:
    image: ros:noetic-ros-core
    tty: true
    network_mode: host
    restart: on-failure
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
    command: stdbuf -o L roscore

